# Generated by Django 4.2.7 on 2025-11-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0003_tapvalidationaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tap',
            new_name='taps_type_110314_idx',
            old_name='taps_type_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tap',
            new_name='taps_locatio_b7e66e_idx',
            old_name='taps_location_idx',
        ),
        migrations.RenameIndex(
            model_name='tapsession',
            new_name='tap_session_token_161759_idx',
            old_name='tap_sessions_token_idx',
        ),
        migrations.RenameIndex(
            model_name='tapsession',
            new_name='tap_session_user_id_dd824d_idx',
            old_name='tap_sessions_user_tap_idx',
        ),
        migrations.RenameIndex(
            model_name='tapsession',
            new_name='tap_session_expires_b0a19a_idx',
            old_name='tap_sessions_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='tapvalidationaudit',
            new_name='tap_validat_device__8b6eda_idx',
            old_name='audit_device_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tapvalidationaudit',
            new_name='tap_validat_token_f22241_idx',
            old_name='audit_token_idx',
        ),
        migrations.RenameIndex(
            model_name='tapvalidationaudit',
            new_name='tap_validat_result_48daef_idx',
            old_name='audit_result_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tapvalidationaudit',
            new_name='tap_validat_created_abcf43_idx',
            old_name='audit_created_idx',
        ),
    ]
