# Generated by Django 4.2.7 on 2025-11-19 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taps', '0004_rename_taps_type_active_idx_taps_type_110314_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, verbose_name='ID do Dispositivo')),
                ('result', models.CharField(choices=[('ok', 'Sucesso'), ('device_not_found', 'Dispositivo Não Encontrado'), ('device_inactive', 'Dispositivo Inativo'), ('device_not_linked', 'Dispositivo Não Vinculado'), ('tap_inactive', 'Tap Inativo'), ('rate_limited', 'Rate Limit Excedido')], max_length=20, verbose_name='Resultado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Uso do Tap',
                'verbose_name_plural': 'Histórico de Uso',
                'db_table': 'tap_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tapusage',
            name='tap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taps.tap', verbose_name='Tap'),
        ),
        migrations.AddField(
            model_name='tapusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='tapusage',
            index=models.Index(fields=['device_id', '-created_at'], name='tap_usage_device__8169d5_idx'),
        ),
        migrations.AddIndex(
            model_name='tapusage',
            index=models.Index(fields=['user', '-created_at'], name='tap_usage_user_id_fb8a03_idx'),
        ),
        migrations.AddIndex(
            model_name='tapusage',
            index=models.Index(fields=['tap', '-created_at'], name='tap_usage_tap_id_47a337_idx'),
        ),
        migrations.AddIndex(
            model_name='tapusage',
            index=models.Index(fields=['result', '-created_at'], name='tap_usage_result_854843_idx'),
        ),
        migrations.AddIndex(
            model_name='tapusage',
            index=models.Index(fields=['-created_at'], name='tap_usage_created_74e582_idx'),
        ),
        # Remover campos e tabelas antigas em ordem segura
        migrations.RunSQL(
            # Deletar tabela transactions primeiro (se existir) para remover foreign keys
            "SET FOREIGN_KEY_CHECKS = 0;",
            reverse_sql="SET FOREIGN_KEY_CHECKS = 1;"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS transactions;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 1;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterModelOptions(
            name='tap',
            options={'ordering': ['name'], 'verbose_name': 'Tap', 'verbose_name_plural': 'Taps'},
        ),
        migrations.RemoveConstraint(
            model_name='tap',
            name='positive_price',
        ),
        migrations.RemoveField(
            model_name='tap',
            name='price_cents',
        ),
        migrations.AlterField(
            model_name='tap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='dose_ml',
            field=models.PositiveIntegerField(default=300, verbose_name='Dose (ml)'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='type',
            field=models.CharField(choices=[('beer', 'Chope'), ('mate', 'Mate')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        # Remover campos das tabelas antigas (após remover foreign keys)
        migrations.RemoveField(
            model_name='tapsession',
            name='tap',
        ),
        migrations.RemoveField(
            model_name='tapsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tapvalidationaudit',
            name='tap',
        ),
        migrations.RemoveField(
            model_name='tapvalidationaudit',
            name='user',
        ),
        migrations.DeleteModel(
            name='TapSession',
        ),
        migrations.DeleteModel(
            name='TapValidationAudit',
        ),
    ]
