# Generated by Django 4.2.7 on 2025-11-19 21:57

from django.db import migrations


def add_columns_if_not_exists(apps, schema_editor):
    """Adiciona colunas user_id e tap_id se não existirem"""
    with schema_editor.connection.cursor() as cursor:
        # Verificar se user_id existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'tap_usage' 
            AND COLUMN_NAME = 'user_id'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("ALTER TABLE tap_usage ADD COLUMN user_id INT NULL")
            cursor.execute("""
                ALTER TABLE tap_usage 
                ADD CONSTRAINT tap_usage_user_id_fk 
                FOREIGN KEY (user_id) REFERENCES auth_user(id) ON DELETE SET NULL
            """)
        
        # Verificar se tap_id existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'tap_usage' 
            AND COLUMN_NAME = 'tap_id'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("ALTER TABLE tap_usage ADD COLUMN tap_id INT NULL")
            cursor.execute("""
                ALTER TABLE tap_usage 
                ADD CONSTRAINT tap_usage_tap_id_fk 
                FOREIGN KEY (tap_id) REFERENCES taps(id) ON DELETE SET NULL
            """)


def remove_columns_if_exists(apps, schema_editor):
    """Remove colunas user_id e tap_id se existirem"""
    with schema_editor.connection.cursor() as cursor:
        # Verificar se user_id existe e remover
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'tap_usage' 
            AND COLUMN_NAME = 'user_id'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE tap_usage DROP FOREIGN KEY IF EXISTS tap_usage_user_id_fk")
            cursor.execute("ALTER TABLE tap_usage DROP COLUMN user_id")
        
        # Verificar se tap_id existe e remover
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'tap_usage' 
            AND COLUMN_NAME = 'tap_id'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE tap_usage DROP FOREIGN KEY IF EXISTS tap_usage_tap_id_fk")
            cursor.execute("ALTER TABLE tap_usage DROP COLUMN tap_id")


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0005_tapusage_remove_tapsession_tap_and_more'),
    ]

    operations = [
        migrations.RunPython(add_columns_if_not_exists, remove_columns_if_exists),
    ]
