# Generated by Django 4.2.7 on 2025-11-19 22:20

from django.db import migrations


def remove_old_tables(apps, schema_editor):
    """Remove tabelas antigas que não são mais usadas"""
    tables_to_remove = ['transactions', 'wallets', 'tap_sessions', 'tap_validation_audit']
    
    with schema_editor.connection.cursor() as cursor:
        # Desabilitar verificação de foreign keys temporariamente
        cursor.execute("SET FOREIGN_KEY_CHECKS = 0")
        
        for table_name in tables_to_remove:
            # Verificar se a tabela existe
            cursor.execute(f"""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = '{table_name}'
            """)
            if cursor.fetchone()[0] > 0:
                # Remover a tabela
                cursor.execute(f"DROP TABLE IF EXISTS {table_name}")
                print(f"Tabela {table_name} removida")
        
        # Reabilitar verificação de foreign keys
        cursor.execute("SET FOREIGN_KEY_CHECKS = 1")


def reverse_remove_old_tables(apps, schema_editor):
    """Não faz nada - não podemos recriar as tabelas antigas"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0006_fix_tapusage_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(remove_old_tables, reverse_remove_old_tables),
    ]
