# Generated by Django 4.2.7 on 2025-11-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_role_fa03e1_idx',
            old_name='user_profiles_role_idx',
        ),
    ]
