# Generated by Django 4.2.7 on 2025-11-19 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_user_profiles_role_idx_user_profil_role_fa03e1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID único do cartão RFID ou dispositivo', max_length=64, unique=True, verbose_name='ID do Dispositivo')),
                ('name', models.CharField(blank=True, help_text='Nome descritivo do dispositivo (ex: Cartão Principal, Cartão Reserva)', max_length=100, verbose_name='Nome do Dispositivo')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('lost', 'Perdido'), ('blocked', 'Bloqueado')], default='active', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionais sobre o dispositivo', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('users', models.ManyToManyField(blank=True, help_text='Usuários que têm acesso a este dispositivo', related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Vinculados')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id'], name='devices_device__c4b5e4_idx'), models.Index(fields=['status'], name='devices_status_9f14cf_idx'), models.Index(fields=['-created_at'], name='devices_created_976a2e_idx')],
            },
        ),
    ]
