# Generated by Django 4.2.7 on 2025-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='valid_transaction_type',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_ced08a_idx',
            old_name='transactions_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_categor_2d1526_idx',
            old_name='transactions_category_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_created_cf5536_idx',
            old_name='transactions_created_idx',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount_cents__lt', 0), ('category__in', ['beer', 'mate']), ('volume_ml__gt', 0)), models.Q(('amount_cents__gt', 0), ('category', 'topup'), ('volume_ml', 0)), _connector='OR'), name='valid_transaction_type'),
        ),
    ]
